### ISSUE TITLE
Error installing on node 0.10.2

### ISSUE THREAD

**Issue by brooly** [fbzhong/node-cityhash#5]
It's not working on node 0.10.2

npm install cityhash
info trying registry request attempt 1 at 13:09:41
http GET https://registry.npmjs.org/cityhash
http 304 https://registry.npmjs.org/cityhash
npm http GET https://registry.npmjs.org/cityhash/-/cityhash-0.0.3.tgz
npm http 200 https://registry.npmjs.org/cityhash/-/cityhash-0.0.3.tgz

> cityhash@0.0.3 install /node_modules/cityhash
> node-gyp rebuild

  CXX(target) Release/obj.target/libcityhash/cityhash/city.o
../cityhash/city.cc:30:10: error: 'city.h' file not found with <angled> include; use "quotes" instead
# include <city.h>

```
     ^~~~~~~~
     "city.h"
```

1 error generated.
make: **\* [Release/obj.target/libcityhash/cityhash/city.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:757:12)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/cityhash
gyp ERR! node -v v0.10.2
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! cityhash@0.0.3 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the cityhash@0.0.3 install script.
npm ERR! This is most likely a problem with the cityhash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cityhash
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "cityhash"
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.16
npm ERR! code ELIFECYCLE

**Comment by brooly** [comment]
I can fix it locally, modifying the sources downloaded, file city.cc changing #include <city.h> with #include "city.h"

info trying registry request attempt 1 at 13:57:44
http GET https://registry.npmjs.org/cityhash
http 304 https://registry.npmjs.org/cityhash

> cityhash@0.0.3 install /node_modules/cityhash
> node-gyp rebuild

  CXX(target) Release/obj.target/libcityhash/cityhash/city.o
  LIBTOOL-STATIC Release/cityhash.a
  CXX(target) Release/obj.target/node-cityhash/binding.o
  SOLINK_MODULE(target) Release/node-cityhash.node
  SOLINK_MODULE(target) Release/node-cityhash.node: Finished
cityhash@0.0.3 node_modules/cityhash

But it still doesn't work, trying to execute for example the tests included with the package i get the following error.:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol node_cityhash_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ()
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by rmg** [comment]
@brooly it has been fixed in the repo, now @fbzhong just needs to roll another release :-)
